In [1]:
import tensorflow as tf

# A] Version check

In [2]:
tf.__version__

'2.3.1'

# B] Tensor constant

In [3]:
sam=tf.constant(10)

In [4]:
sam

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
sam.numpy()

10

In [8]:
sam.dtype

tf.int32

In [9]:
sam.shape    #O-D

TensorShape([])

In [10]:
sam1=tf.constant([[4,2],[3,1]])
sam1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [3, 1]])>

In [11]:
sam1.numpy()

array([[4, 2],
       [3, 1]])

In [12]:
sam1.dtype

tf.int32

In [13]:
sam1.shape

TensorShape([2, 2])

In [14]:
print(tf.constant(10))

tf.Tensor(10, shape=(), dtype=int32)


In [15]:
print(tf.constant([1,2]))

tf.Tensor([1 2], shape=(2,), dtype=int32)


# C] tf.ones and tf.zeros : Way to generate constants

In [16]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [18]:
print(tf.ones(shape=(1,2)))

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)


In [21]:
print(tf.zeros(shape=(4,2)))   #(R,C)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)


# D] Adding constants

In [22]:
const1=tf.constant([[3,4,5],[3,4,5]])

In [23]:
const2=tf.constant([[1,2,3],[1,2,3]])

In [24]:
result=tf.add(const1,const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


# E] Random constant

In [25]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.72712314,  0.8808812 ],
       [-2.2451656 , -0.5922608 ]], dtype=float32)>

In [28]:
tf.random.normal(shape=(3,2),mean=0,stddev=1)    #normal means normal distribution

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.16308041,  1.968203  ],
       [ 0.18119177, -0.10223323],
       [ 1.5297413 , -0.0454156 ]], dtype=float32)>

# F] Variables

In [30]:
var0=24
var1=tf.Variable(40)

In [32]:
var0    #python variabe

24

In [33]:
var1    #TF variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=40>

In [34]:
tensor1=tf.Variable([[1,2,3],[3,4,5]])

In [35]:
tensor1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]])>

In [36]:
#reshape : while reshaping, the number of elements should not change

In [37]:
tensor2=tf.reshape(tensor1, [6,1])

In [38]:
tensor2

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [3],
       [4],
       [5]])>

# G] Rank of tensor : Lowest level of decomposition of dataset


In [39]:
tensor1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]])>

In [41]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# H] Slicing

In [42]:
tensor1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]])>

In [43]:
tensor1[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [44]:
tensor1[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>

In [46]:
tensor1[0][2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [47]:
tensor1[1][1]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [48]:
tensor1[1][0]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# I] Tensorflow Maths operations

In [49]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b

In [51]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.3328464 , -0.59247255],
       [ 0.18074647, -0.12323022]], dtype=float32)>

In [52]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.42904025, -0.26715043],
       [-0.80521184, -1.1269112 ]], dtype=float32)>

In [53]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.90380615, -0.85962296],
       [-0.62446535, -1.2501414 ]], dtype=float32)>

In [55]:
d=tf.square(c)
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.81686556, 0.7389516 ],
       [0.38995698, 1.5628535 ]], dtype=float32)>

# J] Matrix multiplication

In [56]:
matrix_u=tf.constant([[1,2,3]])
matrix_v=tf.constant([[4,5,6]])

In [58]:
tf.matmul(matrix_u,tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]])>

# K] Squared difference of tensors

In [60]:
varx=[4,5,6,12]
vary=8
varz=tf.math.squared_difference(varx,vary)

In [61]:
varz

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([16,  9,  4, 16])>